### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by karawoo** [kelshmo/fvToTable#1]
This looks really good @kelshmo! 🎉 I'm putting my review here in a single issue so it's all in one place, organized by function with a few extra comments at the end.

### `mod_table()`

This looks good to me! I am not running into any unix timestamp errors when I run the code. If you want to exit the function early if there are no changes, you can put `return()` wherever you want to exit.

### `check_etag()` and `check_version()`

I'm curious why these functions paste the etag and synID together? Is it so that you can retain the synID for the output? If so, maybe an anti join on etag/version and id columns would be better as it would be more robust to different ordering of the rows (though I see you've updated `identical()` to `setequal()`, so this is maybe less of an issue).

It's generally recommended to use `vapply()` instead of `sapply()` when programming. In interactive use `sapply()` is fine, but it can produce some strange and errors if it gets an unexpected input. `vapply()` is usually safer.

It looks like these functions have 3 possible outputs:

1. `c("No changes to existing annotations")`, if the etags/versions are identical between the fv and table
2. A vector of synIDs if the file view contains etags/versions that the table lacks
3. An empty list if the table contains file etags/versions that the file view lacks

Does this sound right? I'm particularly wondering about 3 and when you would want the empty list.

Also, I think `check_etag()` might report some false positives. If someone uploads a new version of the file (even if the contents and annotations are the same), it will generate a new etag that will get picked up by `check_etag()` and turned into `"Annotations modified"` by `mod_table()`. So if you really only want to catch when the annotations change, you might need to look at all the keys and values.

### `coalesce_join()`

If I'm following correctly, the following lines appear to get the original names of the columns that get suffixes added to them in the join:

```r
to_coalesce <- names(joined)[!names(joined) %in% cols]
suffix_used <- suffix[ifelse(endsWith(to_coalesce, suffix[1]), 1, 2)]
to_coalesce <- unique(substr(
  to_coalesce,
  1,
  nchar(to_coalesce) - nchar(suffix_used)
))
```

I can't think of a scenario in which these columns wouldn't have been present in the original data, so I think you could shorten this by looking for the columns in the original data that don't exactly match those in the joined data:

```r
to_coalesce <- setdiff(c(names(x), names(y)), names(joined))
```

### Code style

You asked me to comment on format/style. I use tidyverse style so have commented according to that, but a lot of these things are more a matter of preference, and overall the code is well formatted and readable.

Some lines are longer than 80 characters, especially the commented lines describing each function, but some code lines as well. For example, tidyverse style at line 33 would be something like this (note how every argument to `ifelse()` gets its own line and is indented 2 spaces in from the previous item, not aligned with the opening `ifelse()` parenthesis):

```r
bound <- dplyr::bind_rows(
  table,
  fv[fv$id %in% new_entries,includeCols]
) %>%
  mutate(
    notes = ifelse(
      id %in% del_entries[!(del_entries %in% current_delIds)],
      c("File removed"),
      notes
    )
  ) %>%
  mutate(
    modifiedOn = ifelse(
      id %in% del_entries[!(del_entries %in% current_delIds)],
      round(as.numeric(base::Sys.time())),
      modifiedOn
    )
  )
```

Lines 24, 40, and 45 are missing spaces after commas.

There are a few places where I might consider assigning some code to a variable to help with readability. For example, I might save `table$id[!(table$notes %in% c("File removed"))])` as `current_table_files` for something before [this line](https://github.com/karawoo/fvToTable/blob/3f729f9cc8da94a80a432e3b0b800484fa949070/mypackage/R/process_functions.R#L29).

The roxygen documentation was helpful and I like that you have structured this in a package-like way. It would need a few additions/modifications to be actually installable as a package. These are useful functions that I could see others wanting to reuse; would you like some help turning it into a complete package? (Or alternatively contributing to syndccutils?)

**Comment by kelshmo** [comment]
> This looks good to me! I am not running into any unix timestamp errors when I run the code. If you want to exit the function early if there are no changes, you can put return() wherever you want to exit.

The timestamp issue is in how the date is displayed in the Synapse table. I will file a Jira.

> I'm curious why these functions paste the etag and synID together?
I started development of these functions back when the backend was going through a etag revamp - all of the etags were identical. Using both synId and etag to identify changes reduces the chance of breaking this script. 

> check_etag() and check_version()
> It looks like these functions have 3 possible outputs:
> 1. c("No changes to existing annotations"), if the etags/versions are identical between the fv and table
> 2. A vector of synIDs if the file view contains etags/versions that the table lacks
> 3. An empty list if the table contains file etags/versions that the file view lacks
Does this sound right? I'm particularly wondering about 3 and when you would want the empty list.

You are correct, this function does not fully consider the case that files have been deleted and now the synId vectors differ between the table and fileview. I like using `anti_join`. I have updated the function to escape option 3. 

> Also, I think check_etag() might report some false positives. If someone uploads a new version of the file (even if the contents and annotations are the same), it will generate a new etag that will get picked up by check_etag() and turned into "Annotations modified" by mod_table(). So if you really only want to catch when the annotations change, you might need to look at all the keys and values.

I check for etag to note annotation changes and file version increments to note files modified. Since I cannot distinguish between annotation or file changes with the etag, I overwrite the more "general" notation of "Annotations modified" from the etag with "Files modified" from the version on line 42. It is a bit hacky to work with Synapse.... 
> `coalesce_join()`

Good suggestion!

> Code style

I passed `usethis::use_tidy_style()` to format to tidy style although the function passes an invisible data frame with the changes that I cannot figure out how to retrieve! It doesn't look like this picks up proper `ifelse()` indentation. Do you use another tool?

Now, I still need to modify the entire script to escape pushing a `synStore` in the case there are 1.  no changes to etag 2.  no changes to version and  3. no rows to add or delete.  Does it make sense to modify `mod_table` to run only if these conditions are met or build the conditions into the `mod_table` function itself? 

>  These are useful functions that I could see others wanting to reuse; would you like some help turning it into a complete package? (Or alternatively contributing to syndccutils?)

yes!

**Comment by karawoo** [comment]
> I passed usethis::use_tidy_style() to format to tidy style although the function passes an invisible data frame with the changes that I cannot figure out how to retrieve!

When I run `usethis::use_tidy_style()` it edits the files and I see the following, is this not what you are seeing?

```
✔ Setting active project to '/Users/kwoo/projects/forks/fvToTable'
Styling  2  files:
 ./mypackage/R/call_functions.R    ℹ 
 ./mypackage/R/process_functions.R ℹ 
────────────────────────────────────────
Status	Count	Legend 
✔ 	0	File unchanged.
ℹ 	2	File changed.
✖ 	0	Styling threw an error.
────────────────────────────────────────
Please review the changes carefully!

✔ Styled project according to the tidyverse style guide
```

It does still leave a few long lines in the `mutate()` calls with `ifelse()`; I would just manually edit those.

> Now, I still need to modify the entire script to escape pushing a synStore in the case there are 1. no changes to etag 2. no changes to version and 3. no rows to add or delete. Does it make sense to modify mod_table to run only if these conditions are met or build the conditions into the mod_table function itself?

I'm not sure I totally follow what the difference in these two options is, but I could imagine a few different ways to accomplish this that would all be fine. I think what I might do is have a new function, `update_table()` or something, that checks the etag/version/rows and either a) exits with a message ("no updates to be made") if nothing has changed, or b) runs `mod_table()` and `store()` if changes have occurred.

**Comment by kelshmo** [comment]
Thanks for the code review - code added to `syndccutils`!
